pipeline {
    agent {
        node {
            label 'nodejs-slave'
        }
    }
    environment {
        SRC_CODE_DIRECTORY = 'reactjs-projects/tictactoe'
    }
    stages {
        stage('Building Dist') {
            steps {
                dir(SRC_CODE_DIRECTORY){
                    sh 'npm install'
                    sh 'npm run build'
                }
            }
        }
        
        stage('Building App Image') {
            steps {
                container(name:'kaniko', shell:'/busybox/sh'){
                    dir(SRC_CODE_DIRECTORY){
                        sh  '''#!/busybox/sh
                            /kaniko/executor --verbosity=debug --force --no-push --destination=./bogusimagenamepath:bogusversion --tarPath runtime-image.tar --dockerfile=Dockerfile --context dir://$(pwd) --ignore-path=/busybox
                            '''
                    }
                }
            }
        }
        
        stage('Saving App Image to Registry') {
            steps {
                // Replacing docker://quay.io/user15/tictactoe:1.0.0 with local artifactory repository.
                //  
                dir(SRC_CODE_DIRECTORY){
                    sh  '''
                        skopeo copy docker-archive:runtime-image.tar docker://192.168.1.101:8082/docker-quickstart-local/uiapps/tictactoe:1.0.0 --dest-tls-verify=false --authfile=/kaniko/.docker/kaniko-secret.json      
                        '''
                }
            }
        }
    }
}
