pipeline {
    agent {
        node {
            label 'nodejs-slave'
        }
    }
    environment {
        SRC_CODE_DIRECTORY = 'reactjs-projects/tictactoe'
        JFROG_CONTAINER_REGISTRY = '192.168.1.101:8082'
        JFROG_CONTAINER_REGISTRY_AUTH_FILE = '/tmp/.docker/.dockerconfigjson'
        IMAGE_NAME = 'tictactoe'
        IMAGE_VERSION = '1.0.0'
        IMAGE_DESTINATION = "docker://${JFROG_CONTAINER_REGISTRY}/docker-local/apps/ui/browser/${IMAGE_NAME}:${IMAGE_VERSION}"
    }
    stages {
        stage('Building App') {
            steps {
                dir(SRC_CODE_DIRECTORY){
                    sh 'npm install'
                    sh 'npm run build'
                }
            }
        }
        
        stage('Building App Image') {
            steps {
                container(name:'kaniko', shell:'/busybox/sh'){
                    dir(SRC_CODE_DIRECTORY){
                        sh  '''#!/busybox/sh
                            /kaniko/executor --verbosity=debug --force --no-push --destination=./bogusimagenamepath:bogusversion --tarPath runtime-image.tar --dockerfile=Dockerfile --context dir://$(pwd) --ignore-path=/busybox
                            '''
                    }
                }
            }
        }
        
        stage('Saving App Image to Registry') {
            steps {
                dir(SRC_CODE_DIRECTORY){
                    sh  '''
                        skopeo copy docker-archive:runtime-image.tar ${IMAGE_DESTINATION} --dest-tls-verify=false --authfile=${JFROG_CONTAINER_REGISTRY_AUTH_FILE}
                        '''
                }
            }
        }
    }
}
